### ISSUE TITLE
README: need to change recommended  value Memory 

### ISSUE THREAD

**Issue by kegly** [citros-garden/aerosandbox_cessna#10]
1024 Mb is not enough, need to change it to 4096

https://github.com/citros-garden/aerosandbox_cessna/blame/e3fcf7157b0a2de6e6b10aeed7e99d7367c9d583/README.md#L122C287-L122C287

**Comment by vovacooper** [comment]
@gtep96 please fix this.

**Comment by gtep96** [comment]
done
